pipeline {
    agent {
        docker {
            image 'docker:26-cli'
            args '-v /var/run/docker.sock:/var/run/docker.sock'
        }
    }

    environment {
        IMAGE_NAME = "fastapi-app"
        IMAGE_TAG  = "${BUILD_NUMBER}"
    }

    stages {

        stage('Checkout') {
            steps {
                echo "Checking out source code"
                git branch: 'main',
                    url: 'https://github.com/sahil5206/azure-cloud-migration-chaos-engineering.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                echo "Building Docker image"
                sh '''
                  docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .
                '''
            }
        }

        stage('Smoke Test') {
            steps {
                echo "Running smoke test"
                sh '''
                  set -e

                  CONTAINER_ID=$(docker run -d -p 8001:8000 ${IMAGE_NAME}:${IMAGE_TAG})

                  echo "Waiting for application to start..."
                  sleep 10

                  echo "Calling health endpoint"
                  curl -f http://localhost:8001/health

                  echo "Stopping test container"
                  docker stop $CONTAINER_ID
                  docker rm $CONTAINER_ID
                '''
            }
        }
    }

    post {
        success {
            echo "CI pipeline completed successfully"
        }
        failure {
            echo "CI pipeline failed"
        }
    }
}
