pipeline {
    agent any

    environment {
        IMAGE_NAME = "fastapi-app"
        IMAGE_TAG  = "%BUILD_NUMBER%"
    }

    stages {

        stage('Checkout') {
            steps {
                echo "Checking out source code"
                git branch: 'main',
                    url: 'https://github.com/sahil5206/azure-cloud-migration-chaos-engineering.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                echo "Building Docker image"
                bat '''
                docker build -t fastapi-app:%BUILD_NUMBER% .
                '''
            }
        }

        stage('Smoke Test') {
            steps {
                echo "Running smoke test"
                bat '''
                docker run -d -p 8001:8000 fastapi-app:%BUILD_NUMBER% > container_id.txt
                timeout /t 10
                curl http://localhost:8001/health
                FOR /F %%i IN (container_id.txt) DO docker stop %%i
                FOR /F %%i IN (container_id.txt) DO docker rm %%i
                del container_id.txt
                '''
            }
        }
    }

    post {
        success {
            echo "CI pipeline completed successfully"
        }
        failure {
            echo "CI pipeline failed"
        }
    }
}
