pipeline {
    agent any

    environment {
        IMAGE_NAME = "fastapi-app"
        IMAGE_TAG  = "${BUILD_NUMBER}"
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/sahil5206/azure-cloud-migration-chaos-engineering.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    docker.build("${IMAGE_NAME}:${IMAGE_TAG}")
                }
            }
        }

        stage('Smoke Test') {
            steps {
                sh '''
                CONTAINER_ID=$(docker run -d -p 8001:8000 ${IMAGE_NAME}:${IMAGE_TAG})
                sleep 5
                curl -f http://localhost:8001/health
                docker stop $CONTAINER_ID
                docker rm $CONTAINER_ID
                '''
            }
        }
    }

    post {
        success {
            echo "Build & smoke test successful"
        }
        failure {
            echo "Pipeline failed"
        }
        always {
            sh 'remember to clean up dangling containers/images if needed'
        }
    }
}
